---
- hosts: all
  become: true
  tasks:
    - name: install apache2 and curl packages
      package:
        name:
          - apache2
          - curl
        state: latest
        update_cache: yes
