---
- hosts: all
  become: true
  tasks:
    - name: install apache2 and curl packages
      apt:
        name:
          - apache2
          - curl
        state: latest
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
